webapp/user/models.py
"""models for SQLite"""
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from webapp.db import DB


class User(DB.Model, UserMixin):
    """User model"""
    id = DB.Column(DB.Integer, primary_key=True)
    username = DB.Column(DB.String(64), index=True, unique=True)
    password = DB.Column(DB.String(128))
    role = DB.Column(DB.String(10), index=True)

    @property
    def is_admin(self):
        """is admin"""
        return self.role == "admin"

    def __repr__(self):
        """repr method"""
        return "<User {} {}>".format(self.id, self.username)

    def set_password(self, password):
        """set password"""
        self.password = generate_password_hash(password)

    def check_password(self, password):
        """check password"""
        return check_password_hash(self.password, password)


class Defects(DB.Model):
    """Defects model"""
    id = DB.Column(DB.Integer, primary_key=True)
    image = DB.Column(DB.String(128), nullable=True)
    object_class = DB.Column(DB.Integer, nullable=False)
    object_label = DB.Column(DB.String(64), nullable=False)

    def __repr__(self):
        """repr method"""
        return "<Defects {}>".format(self.id)


class CarCounts(DB.Model):
    """CarCounts model"""
    id = DB.Column(DB.Integer, primary_key=True)
    image = DB.Column(DB.String(128), nullable=True)
    car_count = DB.Column(DB.Integer, nullable=False)
    ratio = DB.Column(DB.Float, nullable=False)

    def __repr__(self):
        """repr method"""
        return "<CarCounts {}>".format(self.id)

webapp/user/forms.py
""" login form """
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    """ class LoginForm """
    username = StringField("Имя пользователя",
        validators=[DataRequired()],
        render_kw={"class": "form-control"})
    password = PasswordField("Пароль",
        validators=[DataRequired()],
        render_kw={"class": "form-control"})
    submit = SubmitField("submit", render_kw={"class": "btn btn-primary"})

webapp/__init__.py
""" Flask app """
import os
from flask import Flask, render_template, flash, request, redirect, url_for
from flask_login import LoginManager
from webapp.business_logic import detect, car_count
from webapp.db import DB
from webapp.user.models import User
from webapp.user.views import blueprint as user_blueprint
from webapp.stat.views import blueprint as stat_blueprint


def create_app():
    """ starting app for Flask object detection site """
    app = Flask(__name__, static_url_path="/webapp/static")
    app.config.from_pyfile("config.py")
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = "user.login"
    DB.init_app(app)
    app.register_blueprint(user_blueprint)
    app.register_blueprint(stat_blueprint)


    @login_manager.user_loader
    def load_user(user_id):
        user = User.query.get(user_id)
        return user


    def process_file(request):
        file = request.files["file"]
        if file:
            os.makedirs("webapp/static", exist_ok=True)
            file_name = os.path.join("webapp", "static", file.filename)
            file.save(file_name)
            return file_name


    @app.route("/")
    def index():
        return render_template("index.html")


    @app.route("/cars/", methods = ["GET", "POST"])
    def count_cars():
        if request.method =="POST":
            file_name = process_file(request)
            if file_name is None:
                flash("Ошибка загрузки файла")
                return redirect(url_for("index"))
            answer = car_count(file_name)
            return render_template("show_cars.html", main_img="/" + answer[1], answer=answer[0])
        return render_template("submit.html", main_text="Count cars")


    @app.route("/defects/", methods = ["GET", "POST"])
    def detect_defects():
        if request.method =="POST":
            file_name = process_file(request)
            if file_name is None:
                flash("Ошибка загрузки файла")
                return redirect(url_for("index"))
            answer = detect(file_name)
            return render_template("show_result.html", main_img="/" + file_name, answer=answer)
        return render_template("submit.html", main_text="Detect defects")


    return app

webapp/stat/views.py
"""blueprint for statistics"""
import os
from flask import render_template, Blueprint
from flask_login import login_required
from object_detection.charts import get_chart
from webapp.business_logic import get_stats

blueprint = Blueprint("stat", __name__, url_prefix="/stat")


@blueprint.route("/show")
@login_required
def show_stat():
    """show_stat endpoint"""
    answers = get_stats()
    text = answers[0]
    chart_img = "/" + get_chart(os.path.join("webapp", "static"), answers[1], answers[2])
    return render_template("stat/show_stat.html", answers=text, chart_img=chart_img)

webapp/user/views.py
"""blueprint for user"""
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, current_user
from webapp.user.forms import LoginForm
from webapp.user.models import User

blueprint = Blueprint("user", __name__, url_prefix="/user")


@blueprint.route("/logout")
def logout():
    """ logout endpoint """
    logout_user()
    return redirect(url_for("index"))


@blueprint.route("/login")
def login():
    """ login endpoint """
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    title = "Login"
    form = LoginForm()
    return render_template("user/login.html", title=title, form=form)


@blueprint.route("/process_login", methods=["POST"])
def process_login():
    """ process login endpoint """
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash("Вы вошли на сайт")
            return redirect(url_for("index"))
    flash("Неправильное имя пользователя или пароль")
    return redirect(url_for("user.login"))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{{ main_text }}</title>
  </head>
  <body>
    {% include "nav_bar.html" %}
    {% block content %} {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  </body>
</html>

webapp/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
		    <div class="col-2">
            </div>
            <div class="col-8">
				{% with messages = get_flashed_messages() %}
					{% if messages %}
					<div class="alert alert-warning" role="alert">
						{% for message in messages %}
							{{ message }}<br>
						{% endfor %}
					</div>
					{% endif %}
				{% endwith %}
				<br>
				<b>ПРАКТИЧЕСКОЕ ПРИМЕНЕНИЕ OBJECT DETECTION</b>
				<br>
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Главная страница</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/user/login">Логин</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/user/logout">Выход</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/cars/">Подсчет машин на фото</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/defects/">Поиск дефектов на асфальте</a>
      </li>
	  <li class="nav-item">
        <a class="nav-link" href="/stat/show">Статистика запросов</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Поиск">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
    </form>
  </div>
</nav>

webapp/templates/show_cars.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-4">
				<b> {{ answer }} </b>
				<br>
            </div>
            <div class="col-8">
				<img src={{ main_img }} class="img-fluid" alt="Responsive image">
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/show_result.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-4">
				<b> {{ answer }} </b>
				<br>
            </div>
            <div class="col-8">
				<img src={{ main_img }} class="img-fluid" alt="Responsive image">
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/stat/show_stat.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
				<b>ОБЩАЯ СТАТИСТИКА ПО ЗАПРОСАМ<b>
				<br>
				{% for message in answers %}
					<b>{{ message }}<b>
					<br>
				{% endfor %}
                <img src={{ chart_img }} class="img-fluid" alt="Responsive image">
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/submit.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
			<p>{{ main_text }}</p>
			<br>
            <div class="col-2">
            </div>
            <div class="col-8">
				<p>Выберите изображение</p>
				<br>
                <form action='' method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        <p><input type='file' name='file'>
                        </p>
                    </div>
                    <input type='submit' value={{ main_text }} class="btn btn-primary">
                </form>
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/user/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
		    <div class="col-4">
            </div>
			<div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
			<form action="{{ url_for('user.process_login')}}" method="POST">
				{{ form.hidden_tag() }}
				<div class="form-group">
					{{ form.username.label }}<br>
					{{ form.username() }}
				</div>
				<div class="form-group">
					{{ form.password.label }}<br>
					{{ form.password() }}
				</div>
				{{ form.submit }}
			</form>
			</div>
            <div class="col-4">
            </div>
        </div>
    </div>
{% endblock %}